batch_size: 4
checkpoint_root: checkpoint/HS-ERGB
dataset: deblur_data
ev_in_channel: 96
first_stage_epoch: 210
has_gt: true
im_in_channel: 3
initializor: kaiming
load_cycle: 15
load_dir: checkpoint/HS-ERGB
load_stage: 2
loss: l1
loss_weight:
- 50
- 1
- 50
- 50
lr: 0.001
lr_decay_min_lr: 1.0e-05
lr_decay_rate: 0.5
lr_decay_steps: 200
lr_scheduler: cosine
model_name: san
num_bins: 16
num_workers: 4
out_channel: 3
predict_ts: null
roi_size:
- 256
- 256
root_path: datasets/HS-ERGB
save_path: results/HS-ERGB
scale_factor: 1
second_stage_cycle: 15
second_stage_epoch: 30
seed: 1226
train: true
warmup_epoch: 10
weight_decay: 0
